import { AEMEntryStatus, AEMEntry } from "../models/AEMEntry";

export const mockAEMData: AEMEntry[] = [
  {
    id: "1",
    country: "Honduras",
    TA: "Oncology",
    asset: "Navitoclax",
    indication: "Acute Lymphocytic Leukemia",
    subclassification: "Adult 1L GLOW",
    status: AEMEntryStatus.REVIEW,
    version: "3",
    modifiedBy: "TST-ABVDev01",
    lastModified: new Date().getTime(),
  },
  {
    id: "2",
    country: "Germany",
    TA: "General Medicide",
    asset: "ABBVNAb/A",
    indication: "HIV Infection",
    subclassification: "",
    status: AEMEntryStatus.DRAFT,
    version: "3",
    modifiedBy: "TST-ABVDev01",
    lastModified: new Date().getTime(),
  },
  {
    id: "3",
    country: "France",
    TA: "Immunology",
    asset: "ABBV-154",
    indication: "Plaque Psoriasis",
    subclassification: "",
    status: AEMEntryStatus.FINAL,
    version: "1",
    modifiedBy: "TST-ABVDev01",
    lastModified: new Date().getTime(),
  },
  {
    id: "4",
    country: "Argentina",
    TA: "General Medicide",
    asset: "ABBVNAb/A",
    indication: "Skin Rash",
    subclassification: "",
    status: AEMEntryStatus.DRAFT,
    version: "1",
    modifiedBy: "TST-ABVDev01",
    lastModified: new Date().getTime(),
  },
  {
    id: "5",
    country: "United States",
    TA: "Immunology",
    asset: "ABBVNA0-123",
    indication: "Plaque Psoriasis",
    subclassification: "ADULT 1L GLOW",
    status: AEMEntryStatus.DRAFT,
    version: "3",
    modifiedBy: "TST-ABVDev01",
    lastModified: new Date().getTime(),
  },
  {
    id: "6",
    country: "Peru",
    TA: "General Medicide",
    asset: "ABBVNAb/A",
    indication: "Funny feeling",
    subclassification: "ADULT 1L GLOW",
    status: AEMEntryStatus.FINAL,
    version: "3",
    modifiedBy: "TST-ABVDev01",
    lastModified: new Date().getTime(),
  },
];
